# Generated by Django 2.0.1 on 2018-03-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180307_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('username', models.CharField(blank=True, max_length=25)),
                ('password1', models.CharField(blank=True, max_length=25)),
                ('password2', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
