# Generated by Django 2.0.1 on 2018-03-07 16:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_choice', models.CharField(choices=[('R', 'Running'), ('P', 'Played'), ('W', 'Waiting')], max_length=8)),
                ('gId', models.CharField(max_length=5)),
                ('QId', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None)),
                ('Total', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eId', models.CharField(default='NULL', max_length=3)),
                ('eName', models.CharField(max_length=50)),
                ('eCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='QId',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='eId',
        ),
        migrations.RenameField(
            model_name='registrationsandparticipations',
            old_name='unpaid',
            new_name='registered',
        ),
        migrations.DeleteModel(
            name='EventDetails',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.AddField(
            model_name='details',
            name='eId',
            field=models.OneToOneField(max_length=5, on_delete='CASCADE', to='core.Event'),
        ),
    ]
